version: '3.8'

services:
  backend:
    container_name: sugraph-backend
    build:
      context: .
      dockerfile: src/server/Dockerfile
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
      - DB_SERVER=host.docker.internal
      - DB_NAME=simulated_data
      - DB_USER=sa
      - DB_PASSWORD=YourStrong!Passw0rd
    networks:
      - sugraph-network
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  nginx-certbot:
    build:
      context: ./nginx_Docker
      dockerfile: nginx-certbot.dockerfile
    ports:
      - '80:80'
      - '443:443'
    container_name: nginx
    restart: always
    volumes:
      - './nginx_Docker/nginx/sites-enabled:/etc/nginx/sites-enabled'
      - './nginx_Docker/nginx-logs:/var/log/nginx'
      - './nginx_Docker/letsencrypt:/etc/letsencrypt'
      - './nginx_Docker/certbot:/var/www/certbot'
    networks:
      - sugraph-network

networks:
  sugraph-network:
    external: true
