version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - '3001:3001'
    networks:
      - sugraph-network

  nginx-certbot:
    image: nginx-certbot
    container_name: nginx
    restart: always
    network_mode: host
    volumes:
      - './nginx/sites-enabled:/etc/nginx/sites-enabled'
      - './nginx-logs:/var/log/nginx'
      - './letsencrypt:/etc/letsencrypt'
    networks:
      - sugraph-network

networks:
  sugraph-network:
    external: true
